name: Update saturn retrieval client files

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    name: Copy files
    
    steps:
      - name: Checkout saturn webpage repo
        uses: actions/checkout@v3
        with:
          path: ./saturn-page
  
      - name: Checkout retrieval client repo
        uses: actions/checkout@main
        with:
          repository: filecoin-project/retrieval-client
          path: ./retrieval-client
          
      - name: Copy all files in filecoin-project/retrieval-client/dist/ to filecoin-saturn/homepage/public
        run: |
          rsync -r ./retrieval-client/dist/* ./saturn-page/public/

      - name: Commit changed files to saturn homepage repo
        run: |
          cd ./saturn-page
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Replicate files from filecoin-project/retrieval-client/dist/"
          git push
